CREATE TABLE public.t_fang_o1fy (
  id              BIGSERIAL PRIMARY KEY,
  url             CHARACTER VARYING(50),
  third_party_id  CHARACTER VARYING(30) NOT NULL UNIQUE,
  header          CHARACTER VARYING(200),
  biz_type        CHARACTER VARYING(10),
  house_type_str  CHARACTER VARYING(10),
  xiao_qu_addr    CHARACTER VARYING(200),
  xiao_qu_name    CHARACTER VARYING(100),
  s_counts        INTEGER,
  t_counts        INTEGER,
  w_counts        INTEGER,
  orientation_str CHARACTER VARYING(5),
  decorate_str    CHARACTER VARYING(10),
  estate_area     NUMERIC(10,5),
  publish_price   NUMERIC(28,5),
  price_unit      CHARACTER VARYING(10),
  unit_price      NUMERIC(28,5),
  floor_counts    INTEGER,
  floor           INTEGER,
  create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  contact_name    CHARACTER VARYING(20),
  contact_mobile  CHARACTER VARYING(20),
  description     CHARACTER VARYING(1000),
  image_path      TEXT,
  updata_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  overview        CHARACTER VARYING(200),
  ext_info        CHARACTER VARYING(200),
  map_process     CHARACTER VARYING(20)
);