CREATE TABLE public.t_fang_pool_district (
  id            BIGSERIAL PRIMARY KEY,
  city_id       BIGINT NOT NULL,
  abbr          CHARACTER VARYING(30) NOT NULL,
  name          CHARACTER VARYING(20) NOT NULL,
  create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name_kw       CHARACTER VARYING(200)
);

CREATE TABLE public.t_fang_pool (
  id            BIGSERIAL PRIMARY KEY,
  url           CHARACTER VARYING(50),
  third_party_id CHARACTER VARYING(30),
  header        CHARACTER VARYING(200),
  biz_type      CHARACTER VARYING(10),
  city_id       BIGINT,
  xiao_qu_name  CHARACTER VARYING(100),
  address       CHARACTER VARYING(200),
  house_type    CHARACTER VARYING(10),
  house_sub_type CHARACTER VARYING(10),
  s_counts      INTEGER,
  t_counts      INTEGER,
  w_counts      INTEGER,
  c_counts      INTEGER,
  yt_counts     INTEGER,
  orientation   CHARACTER VARYING(5),
  decorate      CHARACTER VARYING(10),
  estate_area   NUMERIC(10,5),
  real_area     NUMERIC(10,5),
  publish_price NUMERIC(28,5),
  price_unit    CHARACTER VARYING(10),
  unit_price    NUMERIC(28,5),
  floor_counts  INTEGER,
  floor         INTEGER,
  floor_type    CHARACTER VARYING(10),
  structure_type CHARACTER VARYING(20),
  build_year    INTEGER,
  heating_type  CHARACTER VARYING(15),
  create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  contact_name  CHARACTER VARYING(20),
  contact_mobile CHARACTER VARYING(20),
  description   CHARACTER VARYING(1000),
  image_path    TEXT,
  update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ext_info      CHARACTER VARYING(200),
  fang_origin   CHARACTER VARYING(20),
  district_id   INTEGER,
  resident      CHARACTER VARYING(1),
  has_elevator  CHARACTER VARYING(1),
  is_deleted    BOOLEAN NOT NULL DEFAULT false
);