BEGIN ;
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guomao', '国贸');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiulongshan', '九龙山');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dawayao', '大瓦窑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beijingnanzhan', '北京南站');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shangezhuang', '善各庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_rongjingdongjie', '荣京东街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tongyunmen', '通运门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_cuigezhuang', '崔各庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lucheng', '潞城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongzhimen', '东直门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liuliqiaodong', '六里桥东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liangxiangdaxuechengxi', '良乡大学城西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huoqiying', '火器营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shuanghe', '双合');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_changying', '常营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_youanmenwai(zaijian)', '右安门外(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_suzhuang', '苏庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huangcunhuochezhan', '黄村火车站');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beijingdaxuedongmen', '北京大学东门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hepingmen', '和平门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shengwuyiyaojide', '生物医药基地');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wangfujingbei(zaijian)', '王府井北(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_songjiazhuang', '宋家庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiaomendong', '角门东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_bajiaoyouleyuan', '八角游乐园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dalianpo', '褡裢坡');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_sanyuanqiao', '三元桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_mudanyuan', '牡丹园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhangguozhuang', '张郭庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongsishitiao', '东四十条');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_pingleyuan(zaijian)', '平乐园(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guogongzhuang', '郭公庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xisi', '西四');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_junshibowuguan', '军事博物馆');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dahongmenqiao(zaijian)', '大红门桥(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_majiabao', '马家堡');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_aolinpikegongyuan', '奥林匹克公园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiananmendong', '天安门东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wuzixueyuanlu', '物资学院路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhushikou', '珠市口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_haidianwuluju', '海淀五路居');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_niwa', '泥洼');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhuxinzhuang', '朱辛庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yizhuanghuochezhan(zaijian)', '亦庄火车站(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_pingguoyuan', '苹果园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hujialou', '呼家楼');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongdan', '东单');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dahongmen', '大红门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yizhuangqiao', '亦庄桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiantandongmen', '天坛东门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huagong', '化工');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xitieying(zaijian)', '西铁营(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hualikan', '花梨坎');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhongguancun', '中关村');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fengbo', '俸伯');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_ciqu', '次渠');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_sunhe', '孙河');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beixinqiao', '北新桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_taiyanggong', '太阳宫');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huilongguandongdajie', '回龙观东大街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beigongmen', '北宫门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wangjingnan', '望京南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dengshikou', '灯市口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lingjinghutong', '灵境胡同');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shuangqiao', '双桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_libafang', '篱笆房');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiukeshu', '九棵树');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guoyuan', '果园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hepingxiqiao', '和平西桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qingnianlu', '青年路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beiyuanlubei', '北苑路北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_sihuidong', '四惠东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wangfujing', '王府井');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_caishikou', '菜市口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_daotian', '稻田');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beishatan', '北沙滩');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gongzhufen', '公主坟');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liuliqiao', '六里桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fengtaikejiyuan', '丰台科技园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yonghegong', '雍和宫');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lianhuaqiao', '莲花桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lincuiqiao', '林萃桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xihongmen', '西红门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huixinxijiebeikou', '惠新西街北口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_haidianhuangzhuang', '海淀黄庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beitucheng', '北土城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gucheng', '古城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qingyuanlu', '清源路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gaomidianbei', '高米店北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guanzhuang', '管庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiananmenxi', '天安门西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_cishousi', '慈寿寺');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chegongzhuangxi', '车公庄西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shilihe', '十里河');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xizhimen', '西直门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beigongdaximen', '北工大西门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qiaowan', '桥湾');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_laiguangying', '来广营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huangqu', '黄渠');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_futong', '阜通');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huixinxijienankou', '惠新西街南口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liudaokou', '六道口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiantongyuannan', '天通苑南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanbalizhuang(zaijian)', '南八里庄(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xiaocun', '肖村');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xixiaokou', '西小口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_baiduizi', '白堆子');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanfaxin', '南法信');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guojiatushuguan', '国家图书馆');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_caihuying(zaijian)', '菜户营(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liufang', '柳芳');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_datunludong', '大屯路东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shenshahai', '什刹海');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tongzhoubeiyuan', '通州北苑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fuchengmen', '阜成门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_anheqiaobei', '安河桥北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_bagou', '巴沟');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_ciqunan', '次渠南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liangxiangdaxuecheng', '良乡大学城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shimen', '石门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiangtai', '将台');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xuanwumen', '宣武门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xidan', '西单');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liujiayao', '刘家窑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dabaotai', '大葆台');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xinjiekou', '新街口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fengtainanlu', '丰台南路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yuanboyuan', '园博园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_sihui', '四惠');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yongdingmenwai', '永定门外');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wangjingxi', '望京西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shahegaojiaoyuan', '沙河高教园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gaomidiannan', '高米店南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_donghuqu', '东湖渠');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guangximen', '光熙门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jingtai', '景泰');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xidiaoyutai', '西钓鱼台');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhangchunqiao', '长春桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yuanmingyuan', '圆明园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fengtaizhan', '丰台站');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guanganmennei', '广安门内');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xitucheng', '西土城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lizeshangwuqu(zaijian)', '丽泽商务区(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tongzhoubeiguan', '通州北关');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_taoranting', '陶然亭');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_anhuaqiao', '安华桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gongyixiqiao', '公益西桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guozhuangzi', '郭庄子');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhongguomeishuguan(zaijian)', '中国美术馆(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_renmindaxue', '人民大学');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huoying', '霍营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guangyangcheng', '广阳城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huilongguan', '回龙观');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chuanmeidaxue', '传媒大学');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_muxiyuannan(zaijian)', '木樨园南(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_keyilu', '科怡路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dajing', '大井');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jintailu', '金台路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fenzhongsi', '分钟寺');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chegongzhuang', '车公庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beijingxizhan', '北京西站');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiugong', '旧宫');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_taoranqiao(zaijian)', '陶然桥(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wufutang(zaijian)', '五福堂(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_baliqiao', '八里桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongshayuan', '东厦园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chengshousi', '成寿寺');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_senlingongyuannanmen', '森林公园南门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_suzhoujie', '苏州街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_baiziwan', '百子湾');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongguantou(zaijian)', '东管头(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yuxin', '育新');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanshao', '南邵');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yizhuangwenhuayuan', '亦庄文化园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qinghuadongluxikou', '清华东路西口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_ciqikou', '磁器口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hufangqiao', '虎坊桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shilibao', '十里堡');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_baishiqiaonan', '白石桥南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_caoqiao', '草桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongdaqiao', '东大桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yonganli', '永安里');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jianguomen', '建国门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhichunli', '知春里');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liangxiangnanguan', '良乡南关');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_pinganli', '平安里');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_panjiayuan', '潘家园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jinsong', '劲松');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_muxiyuanbei(zaijian)', '木樨园北(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_caofang', '草房');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wanzi', '湾子');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dajiaoting', '大郊亭');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_T2hangzhanlou', 'T2航站楼');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yihezhuang', '义和庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lishuiqiao', '立水桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hongmiao(zaijian)', '红庙(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tongjinanlu', '同济南路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jishuitan', '积水潭');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_puhuangyu', '蒲黄榆');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_longze', '龙泽');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gonghuacheng', '巩华城');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_aotizhongxin', '奥体中心');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shengmingkexueyuan', '生命科学园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fengtaidongdajie', '丰台东大街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shahe', '沙河');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shisanlingjingqu(zaijian)', '十三陵景区(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jintaixizhao', '金台夕照');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qianmen', '前门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huanlegujingqu', '欢乐谷景区');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chaoyangmen', '朝阳门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiaomenxi', '角门西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongwuyuan', '动物园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chaoyanggongyuan(zaijian)', '朝阳公园(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_qilizhuang', '七里庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiantongyuanbei', '天通苑北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liangmaqiao', '亮马桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_anzhenmen', '安贞门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_changpingdongguan', '昌平东关');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhangzizhonglu', '张自忠路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tianqiao(zaijian)', '天桥(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wudaokou', '五道口');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guanzhuang1', '关庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_andingmen', '安定门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guangqumenwai', '广渠门外');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_heyi(zaijian)', '和义(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_maquanying', '马泉营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_babaoshan', '八宝山');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jinghailu', '经海路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beiyunhexi', '北运河西');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tuqiao', '土桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_changping', '昌平');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yuzhilu', '育知路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_haojiafu', '郝家府');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wanyuanjie', '万源街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_pingxifu', '平西府');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_lishuiqiaonan', '立水桥南');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dazhongsi', '大钟寺');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fangzhuang', '方庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liyuan', '梨园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_daguanying', '达官营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanlouzizhuang', '南楼梓庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huangcunxidajie', '黄村西大街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guozhan', '国展');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zaoyuan', '枣园');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liuyingmen(zaijian)', '六营门(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chedaogou', '车道沟');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wanshoulu', '万寿路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiandemen', '健德门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhangchunjie', '长椿街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_hepinglibeijie', '和平里北街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dawanglu', '大望路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shoujingmao', '首经贸');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beiyunhedong', '北运河东');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zaoying', '枣营');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tuanjiehu', '团结湖');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jiaohuachang', '焦化厂');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shaoyaoju', '芍药居');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shunyi', '顺义');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gaojiayuan(zaijian)', '高家园(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guangqumennei', '广渠门内');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiantongyuan', '天通苑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yongtaizhuang', '永泰庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_chongwenmen', '崇文门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_andelibeijie', '安德里北街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fatou', '垡头');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhichunlu', '知春路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_weigongcun', '魏公村');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beihaibei', '北海北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_T3hangzhanlou', 'T3航站楼');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wukesong', '五棵松');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_liangxiangdaxuechengbei', '良乡大学城北');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xierqi', '西二旗');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_muxide', '木樨地');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_yuquanlu', '玉泉路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xiaohongmen', '小红门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_fuxingmen', '复兴门');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_gaobeidian', '高碑店');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shangde', '上地');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_wangjing', '望京');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xiwade(zaijian)', '西洼地(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xingong', '新宫');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_zhangyang', '长阳');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongfengbeiqiao', '东风北桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shuangjing', '双井');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beishaowa(zaijian)', '北邵洼(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beiyuan', '北苑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_dongsi', '东四');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_anlilu', '安立路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_jijiamiao', '纪家庙');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanluoguxiang', '南锣鼓巷');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xiyuan', '西苑');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nongyezhanlanguan', '农业展览馆');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_changpingxishankou(zaijian)', '昌平西山口(在建)');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_rongchangdongjie', '荣昌东街');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_houshayu', '后沙峪');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_tiangongyuan', '天宫院');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_nanlishilu', '南礼士路');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_xiju', '西局');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_beijingzhan', '北京站');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_linheli', '临河里');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_huayuanqiao', '花园桥');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_shiliuzhuang', '石榴庄');
INSERT INTO t_station( station_abbr, station_name) VALUES ('bjs_guloudajie', '鼓楼大街');
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_1haoxian','1号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_pingguoyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_gucheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_bajiaoyouleyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_babaoshan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_yuquanlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_wukesong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_wanshoulu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_gongzhufen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_junshibowuguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_muxide';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_nanlishilu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_fuxingmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_xidan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_tiananmenxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_tiananmendong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_wangfujing';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_dongdan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_jianguomen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_yonganli';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_guomao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_dawanglu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_sihui';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_1haoxian' AND s.station_abbr = 'bjs_sihuidong';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_2haoxian','2号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_jishuitan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_guloudajie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_andingmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_yonghegong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_dongzhimen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_dongsishitiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_chaoyangmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_jianguomen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_beijingzhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_chongwenmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_qianmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_hepingmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_xuanwumen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_zhangchunjie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_fuxingmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_fuchengmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_chegongzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_2haoxian' AND s.station_abbr = 'bjs_xizhimen';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_4haoxian','4号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_tiangongyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_shengwuyiyaojide';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_yihezhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_huangcunhuochezhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_huangcunxidajie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_qingyuanlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_zaoyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_gaomidiannan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_gaomidianbei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xihongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xingong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_gongyixiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_jiaomenxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_majiabao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_beijingnanzhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_taoranting';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_caishikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xuanwumen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xidan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_lingjinghutong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xisi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_pinganli';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xinjiekou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xizhimen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_dongwuyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_guojiatushuguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_weigongcun';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_renmindaxue';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_haidianhuangzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_zhongguancun';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_beijingdaxuedongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_yuanmingyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_xiyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_beigongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_4haoxian' AND s.station_abbr = 'bjs_anheqiaobei';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_5haoxian','5号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_tiantongyuanbei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_tiantongyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_tiantongyuannan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_lishuiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_lishuiqiaonan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_beiyuanlubei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_datunludong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_huixinxijiebeikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_huixinxijienankou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_hepingxiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_hepinglibeijie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_yonghegong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_beixinqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_zhangzizhonglu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_dongsi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_dengshikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_dongdan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_chongwenmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_ciqikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_tiantandongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_puhuangyu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_liujiayao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_5haoxian' AND s.station_abbr = 'bjs_songjiazhuang';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_6haoxian','6号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_lucheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_dongshayuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_haojiafu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_beiyunhedong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_beiyunhexi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_tongyunmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_tongzhoubeiguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_wuzixueyuanlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_caofang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_changying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_huangqu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_dalianpo';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_qingnianlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_shilibao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_jintailu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_hujialou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_dongdaqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_chaoyangmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_dongsi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_nanluoguxiang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_beihaibei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_pinganli';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_chegongzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_chegongzhuangxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_baishiqiaonan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_huayuanqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_cishousi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_6haoxian' AND s.station_abbr = 'bjs_haidianwuluju';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_7haoxian','7号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_beijingxizhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_wanzi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_daguanying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_guanganmennei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_caishikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_hufangqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_zhushikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_qiaowan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_ciqikou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_guangqumennei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_guangqumenwai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_jiulongshan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_dajiaoting';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_baiziwan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_huagong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_nanlouzizhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_huanlegujingqu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_fatou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_shuanghe';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_7haoxian' AND s.station_abbr = 'bjs_jiaohuachang';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_8haoxian','8号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_zhuxinzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_yuzhilu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_pingxifu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_huilongguandongdajie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_huoying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_yuxin';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_xixiaokou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_yongtaizhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_lincuiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_senlingongyuannanmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_aolinpikegongyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_aotizhongxin';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_beitucheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_anhuaqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_andelibeijie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_guloudajie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_shenshahai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_nanluoguxiang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_zhongguomeishuguan(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_wangfujingbei(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_tianqiao(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_yongdingmenwai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_muxiyuanbei(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_muxiyuannan(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_dahongmenqiao(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_heyi(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_xiwade(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_liuyingmen(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_8haoxian' AND s.station_abbr = 'bjs_wufutang(zaijian)';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_9haoxian','9号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_guojiatushuguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_baishiqiaonan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_baiduizi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_junshibowuguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_beijingxizhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_liuliqiaodong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_liuliqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_qilizhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_fengtaidongdajie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_fengtainanlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_keyilu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_fengtaikejiyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_9haoxian' AND s.station_abbr = 'bjs_guogongzhuang';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_10haoxian','10号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_chedaogou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_xiju';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_liuliqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_lianhuaqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_gongzhufen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_xidiaoyutai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_cishousi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_zhangchunqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_huoqiying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_bagou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_suzhoujie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_haidianhuangzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_zhichunli';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_zhichunlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_xitucheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_mudanyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jiandemen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_beitucheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_anzhenmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_huixinxijienankou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_shaoyaoju';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_taiyanggong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_sanyuanqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_liangmaqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_nongyezhanlanguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_tuanjiehu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_hujialou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jintaixizhao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_guomao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_shuangjing';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jinsong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_panjiayuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_shilihe';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_fenzhongsi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_chengshousi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_songjiazhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_shiliuzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_dahongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jiaomendong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jiaomenxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_caoqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_jijiamiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_shoujingmao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_fengtaizhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_10haoxian' AND s.station_abbr = 'bjs_niwa';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_13haoxian','13号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_xizhimen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_dazhongsi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_zhichunlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_wudaokou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_shangde';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_xierqi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_longze';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_huilongguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_huoying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_lishuiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_beiyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_wangjingxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_shaoyaoju';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_guangximen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_liufang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_13haoxian' AND s.station_abbr = 'bjs_dongzhimen';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_14haoxian(dongduan)','14号线(东段)');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_beijingnanzhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_puhuangyu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_fangzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_dongguantou(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_lizeshangwuqu(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_caihuying(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_xitieying(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_youanmenwai(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_taoranqiao(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_yongdingmenwai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_jingtai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_nanbalizhuang(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_beigongdaximen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_pingleyuan(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_hongmiao(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_jintailu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_chaoyanggongyuan(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_zaoying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_dongfengbeiqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_jiangtai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_gaojiayuan(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_wangjingnan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_futong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_wangjing';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_donghuqu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_laiguangying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(dongduan)' AND s.station_abbr = 'bjs_shangezhuang';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_14haoxian(xiduan)','14号线(西段)');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_zhangguozhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_yuanboyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_xiju';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_qilizhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_dajing';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_guozhuangzi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_14haoxian(xiduan)' AND s.station_abbr = 'bjs_dawayao';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_15haoxian','15号线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_fengbo';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_shunyi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_shimen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_nanfaxin';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_houshayu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_hualikan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_guozhan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_sunhe';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_maquanying';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_cuigezhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_wangjing';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_wangjingxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_guanzhuang1';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_datunludong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_anlilu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_aolinpikegongyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_beishatan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_liudaokou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_15haoxian' AND s.station_abbr = 'bjs_qinghuadongluxikou';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_batongxian','八通线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_sihui';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_sihuidong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_gaobeidian';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_chuanmeidaxue';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_shuangqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_guanzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_baliqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_tongzhoubeiyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_guoyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_jiukeshu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_liyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_linheli';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_batongxian' AND s.station_abbr = 'bjs_tuqiao';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_yizhuangxian','亦庄线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_songjiazhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_xiaocun';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_xiaohongmen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_jiugong';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_yizhuangqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_yizhuangwenhuayuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_wanyuanjie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_rongjingdongjie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_rongchangdongjie';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_tongjinanlu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_jinghailu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_ciqunan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_ciqu';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_yizhuangxian' AND s.station_abbr = 'bjs_yizhuanghuochezhan(zaijian)';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_changpingxian','昌平线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_xierqi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_shengmingkexueyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_zhuxinzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_gonghuacheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_shahe';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_shahegaojiaoyuan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_nanshao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_beishaowa(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_changpingdongguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_changping';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_shisanlingjingqu(zaijian)';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_changpingxian' AND s.station_abbr = 'bjs_changpingxishankou(zaijian)';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_fangshanxian','房山线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_suzhuang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_liangxiangnanguan';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_liangxiangdaxuechengxi';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_liangxiangdaxuecheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_liangxiangdaxuechengbei';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_guangyangcheng';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_libafang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_zhangyang';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_daotian';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_dabaotai';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_fangshanxian' AND s.station_abbr = 'bjs_guogongzhuang';
INSERT INTO t_line (city_id, line_abbr, line_name) VALUES (1, 'bjl_jichangxian','机场线');
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_jichangxian' AND s.station_abbr = 'bjs_dongzhimen';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_jichangxian' AND s.station_abbr = 'bjs_sanyuanqiao';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_jichangxian' AND s.station_abbr = 'bjs_T3hangzhanlou';
INSERT INTO t_line_station_rel(line_id,station_id) SELECT   l.id,  s.id FROM t_line l, t_station s WHERE l.line_abbr = 'bjl_jichangxian' AND s.station_abbr = 'bjs_T2hangzhanlou';

COMMIT ;